modLoader="javafml"
loaderVersion="[35,)"
license="MIT License"
issueTrackerURL="https://github.com/DaLumma/farmersdelight_cookbook_addon/issues"

[[mods]]
    modId="fd_cookbook"
    version="1.2"
    displayName="Farmers Delight Cookbook"
    displayURL="https://github.com/DaLumma"
    logoFile="logo.png"
    credits="Thanks to Vectorwing for making Farmers Delight"
    authors="DaLumma"
    description="This is a mod that adds a Cookbook to Farmers Delight"

[[dependencies.fd_cookbook]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fd_cookbook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fd_cookbook]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16.4-50,)"
    side="BOTH"

[[dependencies.fd_cookbook]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[1.16.3-0.3.2,)"
    ordering = "AFTER"
    side = "BOTH"
